In [ ]:
def greet():
  print("Hello!")

greet()
greeting = greet()

Hello!
Hello!


In [ ]:
def applyfunction(func,val):
  return func(val)

print(applyfunction(lambda x: x * 5,5))

25


In [ ]:
def multiplier(factor):
  def multiply(num):
    return num * factor
  return multiply

multiply5 = multiplier(5)
print(multiply5(2))

10


In [ ]:
def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)

print(factorial(5))

120


In [ ]:
def greet(name):
  """This function greets the user by their name."""
  print(f"Hello {name}!")

greet("Alice")

help(greet)

Hello Alice!
Help on function greet in module __main__:

greet(name)
    This function greets the user by their name.



In [ ]:
x = 10 # Global Variable
def random():
  x = 5 # Local Variable
  print("Inside Function",x)


random()
print("Outside Function",x)

Inside Function 5
Outside Function 10


In [ ]:
z = 10
def random():
  global z
  z = 5
  print("Inside Function",z)

random()
print("Outside Function",z)

Inside Function 5
Outside Function 5


In [ ]:
def outer():
  x = 5  # Enclosed Variable
  def inner():
    nonlocal x
    x = 10
    print("Inner Function",x)
  inner()
  print("Outer Function",x)

outer()

Inner Function 10
Outer Function 10


In [ ]:
def addnums(a,b):
  return a+b

print(addnums(1,2))

3


In [ ]:
import numpy as np

In [ ]:
lst = [1,2,3]
np_array = np.array(lst)
print(type(lst))
print(type(np_array))
print(np_array.shape)

<class 'list'>
<class 'numpy.ndarray'>
(3,)


In [ ]:
array1d = np.array([1,2,3])
print(array1d.ndim)
array2d = np.array([[1,2],[3,4],[5,6]])
print(array2d.ndim)

1
2


In [ ]:
zero_array = np.zeros((3,2))
print(zero_array)
one_array = np.ones((3,2))
print(one_array)
full_array = np.full((3,2),10)
print(full_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[10 10]
 [10 10]
 [10 10]]


In [ ]:
linspace_array = np.linspace(0,10,6)
print(linspace_array)

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
arange_array = np.arange(0,10,3)
print(arange_array)

[0 3 6 9]


In [ ]:
random_array = np.random.rand(3,2)
print(random_array)
intrandm_array = np.random.randint(1,10,(3,2))
print(intrandm_array)

[[0.44841306 0.14377862]
 [0.07445114 0.99211794]
 [0.85979303 0.00658373]]
[[9 9]
 [8 6]
 [3 4]]


In [ ]:
np_array = np.array([[1,2,3],[4,5,6],[5,10,15]])
print(np_array[1,2])
print(np_array.shape)
print(np_array.size)
print(np_array.ndim)

6
(3, 3)
9
2


In [ ]:
np_array = np.array([[1,2,3],[4,5,6],[5,10,15]])
print(np_array[0:2,0:2])

[[1 2]
 [4 5]]


In [ ]:
np_array = np.array([[1,2,3],[4,5,6],[5,10,15]])
print(np_array.dtype)
np_array = np_array.reshape(-1,1)
print(np_array)
np_array = np.array([1,2,3,4,5,6])
np_array = np_array.reshape(2,3)
print(np_array)

int64
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 5]
 [10]
 [15]]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print(np.concatenate((arr1,arr2),axis=1))
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
print(np.min(arr1))
print(np.max(arr1))
print(np.sum(arr2))
print(np.mean(arr1))
print(np.median(arr2))
print(np.std(arr1))
print(np.sin(arr1))

1
6
57
3.5
9.5
1.707825127659933
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [ ]:
print(arr1[1,2])
print(arr1[1,1:3])
print(arr2[0,-1])

6
[5 6]
9


In [ ]:
arr3 = np.array([1,2,3,4,5,6,7])
print(arr3[1:6:2])
print(arr3[::3])
print(arr3[::-1])

[2 4 6]
[1 4 7]
[7 6 5 4 3 2 1]


In [ ]:
print(arr1)
print(arr1.T)
print(arr1[0:2,1:3])
print(arr1[:,::2])

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[2 3]
 [5 6]]
[[1 3]
 [4 6]]


In [ ]:
print(arr1.flatten())
result1 = np.where(arr1 > 4)
print(result1)
result2 = np.where(arr3 > 3)
print(result2)

[1 2 3 4 5 6]
(array([1, 1]), array([1, 2]))
(array([3, 4, 5, 6]),)


In [ ]:
print(arr3)
print(np.sort(arr3))
print(np.take(arr3,[2,4]))
np.put(arr3,[2,4],[10,11])
print(arr3)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[3 5]
[ 1  2 10  4 11  6  7]
